site_name: Documentation template

nav:
    - Tutorials:
        - Tutorials: tutorials/tutorials.md
    - How-to Guides:
        - How-to: howto/howto.md
    - Reference:
        - Getting catalogs: reference/download.md
    - Discussions:
        - Discussions: discussions/discussions.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme: readthedocs
